### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by her-mes** [WickrInc/wickrio_web_interface#2]
There is no link or description on where to find `WickrIO_Client_REST_API.doc` as per the [README](WickrIO_Client_REST_API.doc).

**Comment by ronmshv** [comment]
Hi,

Thanks for pointing this out, I will add the link in to the readme. You can find all the relevant information here: https://wickrinc.github.io/wickrio-docs/#web-interface-rest-api-rest-api-overview
